// flow-typed signature: 4ab07f819b1d82465198dd477f189d04
// flow-typed version: <<STUB>>/graphql-subscriptions_v^0.3.1/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-subscriptions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-subscriptions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-subscriptions/dist/index' {
  declare module.exports: any;
}

declare module 'graphql-subscriptions/dist/pubsub' {
  declare module.exports: any;
}

declare module 'graphql-subscriptions/dist/test/tests' {
  declare module.exports: any;
}

declare module 'graphql-subscriptions/dist/validation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-subscriptions/dist/index.js' {
  declare module.exports: $Exports<'graphql-subscriptions/dist/index'>;
}
declare module 'graphql-subscriptions/dist/pubsub.js' {
  declare module.exports: $Exports<'graphql-subscriptions/dist/pubsub'>;
}
declare module 'graphql-subscriptions/dist/test/tests.js' {
  declare module.exports: $Exports<'graphql-subscriptions/dist/test/tests'>;
}
declare module 'graphql-subscriptions/dist/validation.js' {
  declare module.exports: $Exports<'graphql-subscriptions/dist/validation'>;
}
