// flow-typed signature: 780dabd1022b008a2780e4fd7db776f2
// flow-typed version: <<STUB>>/koa-generic-session_v^1.11.5/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-generic-session'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-generic-session' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-generic-session/lib/memory_store' {
  declare module.exports: any;
}

declare module 'koa-generic-session/lib/session' {
  declare module.exports: any;
}

declare module 'koa-generic-session/lib/store' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-generic-session/index' {
  declare module.exports: $Exports<'koa-generic-session'>;
}
declare module 'koa-generic-session/index.js' {
  declare module.exports: $Exports<'koa-generic-session'>;
}
declare module 'koa-generic-session/lib/memory_store.js' {
  declare module.exports: $Exports<'koa-generic-session/lib/memory_store'>;
}
declare module 'koa-generic-session/lib/session.js' {
  declare module.exports: $Exports<'koa-generic-session/lib/session'>;
}
declare module 'koa-generic-session/lib/store.js' {
  declare module.exports: $Exports<'koa-generic-session/lib/store'>;
}
