// flow-typed signature: db2bf00c8920d7ffed185c39feededae
// flow-typed version: <<STUB>>/subscriptions-transport-ws_v^0.5.5-alpha.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'subscriptions-transport-ws'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'subscriptions-transport-ws' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'subscriptions-transport-ws/browser/client' {
  declare module.exports: any;
}

declare module 'subscriptions-transport-ws/dist/client-index' {
  declare module.exports: any;
}

declare module 'subscriptions-transport-ws/dist/client' {
  declare module.exports: any;
}

declare module 'subscriptions-transport-ws/dist/graphiql-fetcher' {
  declare module.exports: any;
}

declare module 'subscriptions-transport-ws/dist/helpers' {
  declare module.exports: any;
}

declare module 'subscriptions-transport-ws/dist/index' {
  declare module.exports: any;
}

declare module 'subscriptions-transport-ws/dist/messageTypes' {
  declare module.exports: any;
}

declare module 'subscriptions-transport-ws/dist/protocols' {
  declare module.exports: any;
}

declare module 'subscriptions-transport-ws/dist/server' {
  declare module.exports: any;
}

declare module 'subscriptions-transport-ws/unpkg-webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'subscriptions-transport-ws/browser/client.js' {
  declare module.exports: $Exports<'subscriptions-transport-ws/browser/client'>;
}
declare module 'subscriptions-transport-ws/dist/client-index.js' {
  declare module.exports: $Exports<'subscriptions-transport-ws/dist/client-index'>;
}
declare module 'subscriptions-transport-ws/dist/client.js' {
  declare module.exports: $Exports<'subscriptions-transport-ws/dist/client'>;
}
declare module 'subscriptions-transport-ws/dist/graphiql-fetcher.js' {
  declare module.exports: $Exports<'subscriptions-transport-ws/dist/graphiql-fetcher'>;
}
declare module 'subscriptions-transport-ws/dist/helpers.js' {
  declare module.exports: $Exports<'subscriptions-transport-ws/dist/helpers'>;
}
declare module 'subscriptions-transport-ws/dist/index.js' {
  declare module.exports: $Exports<'subscriptions-transport-ws/dist/index'>;
}
declare module 'subscriptions-transport-ws/dist/messageTypes.js' {
  declare module.exports: $Exports<'subscriptions-transport-ws/dist/messageTypes'>;
}
declare module 'subscriptions-transport-ws/dist/protocols.js' {
  declare module.exports: $Exports<'subscriptions-transport-ws/dist/protocols'>;
}
declare module 'subscriptions-transport-ws/dist/server.js' {
  declare module.exports: $Exports<'subscriptions-transport-ws/dist/server'>;
}
declare module 'subscriptions-transport-ws/unpkg-webpack.config.js' {
  declare module.exports: $Exports<'subscriptions-transport-ws/unpkg-webpack.config'>;
}
